In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.sum()) 

10


In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.mean()) 

2.5


In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.min())

1


In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.max()) 

4


In [5]:
import numpy as np 
import random
array = np.random.randint(16,size=(4,4)) 
print("Input Array: \n",array) 
print("largest number in x axis: ",np.max(array,axis=1)) 
print("largest number in y axis: ",np.max(array,axis=0))



Input Array: 
 [[14  4  6  0]
 [10  5 11  3]
 [ 9  8  9  5]
 [12 12  0  5]]
largest number in x axis:  [14 11  9 12]
largest number in y axis:  [14 12 11  5]


In [6]:
import numpy as np 
import random 
array = np.random.randint(16,size=(4,4)) 
print("Input Array: \n",array) 

print("Smallest number in x axis: ",np.min(array,axis=1)) 
print("Smallest number in y axis: ",np.min(array,axis=0))

Input Array: 
 [[ 5 13  4  6]
 [ 6  4  6 10]
 [ 1 11  2  4]
 [ 8 13  9 10]]
Smallest number in x axis:  [4 4 1 8]
Smallest number in y axis:  [1 4 2 4]


In [7]:
print(arr.std())  

1.118033988749895


In [8]:



print(np.sin(arr))  
# Output: [0.84147098 0.90929743 0.14112001]

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [9]:
arr = np.array([1, 2, 3])
print(arr + 2)  
# Output: [3 4 5]

[3 4 5]


In [10]:
import numpy as np 
import random

array = np.random.randint([1,2,3,4])
squared = list(map(lambda x: x**2, arr))
print("Squared using map:", squared)
#Example of map()


Squared using map: [np.int64(1), np.int64(4), np.int64(9)]


In [11]:
def square(number):
    return number * number

nums = [1, 2, 3, 4]
squared_numbers = list(map(square, nums))

print(squared_numbers)






[1, 4, 9, 16]


In [12]:
nums1= [1,2,3,4,5,6]
squareOfnums1 = list(map(lambda n:n*n,nums1))
print(squareOfnums1)

[1, 4, 9, 16, 25, 36]


In [13]:
def is_even(n):
    if n % 2 ==0:
        return True
    else:
        return False
    
nums = [1,2,3,4]
evens = list(filter(is_even,nums))
print(evens)

[2, 4]


In [14]:
from functools import reduce

def sum_all(a, b): 
    return a + b 

nums = [1, 2, 3, 4] 
total = reduce(sum_all, nums) 

print(total)


10


In [16]:
total = reduce(lambda x, y: x + y, arr)
print("Sum using reduce:", total)


Sum using reduce: 6


In [26]:
import pandas as pd
data = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print(data)

a    10
b    20
c    30
d    40
dtype: int64


In [27]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['Delhi', 'Mumbai', 'Bangalore']
}
df = pd.DataFrame(data)
print(df)

      Name  Age       City
0    Alice   25      Delhi
1      Bob   30     Mumbai
2  Charlie   35  Bangalore


In [3]:
import pandas as pd
df = pd.read_csv('rkm-001.csv')


df.to_csv('output.csv', index=False)

df.head()         
df.tail()         
df.info()         
df.describe()     
df.columns        
df.shape          




print(df['Name'])

print(df.loc[0])  

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    5 non-null      object
 1   Age     5 non-null      int64 
 2   City    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes
0      Alice
1        Bob
2    Charlie
3      David
4        Eva
Name: Name, dtype: object
Name       Alice
Age           30
City    New York
Name: 0, dtype: object
